# Staging overrides - use with --env-file env/env.staging
# Production builds with DEBUG logging and app-only port exposure
#
# Usage: docker compose --env-file env/env.staging up -d
#
# Staging configuration:
# - LOG_LEVEL: DEBUG (for troubleshooting)
# - restart: always (production-like behavior)
# - No port mappings (reverse proxy handles external access)
# - Production build targets (code baked into images)

services:
  api:
    build:
      target: production
    environment:
      LOG_LEVEL: DEBUG

  bot:
    build:
      target: production
    environment:
      LOG_LEVEL: DEBUG

  notification-daemon:
    build:
      target: production
    environment:
      LOG_LEVEL: DEBUG

  status-transition-daemon:
    build:
      target: production
    environment:
      LOG_LEVEL: DEBUG

  frontend:
    build:
      target: production
    depends_on:
      api:
        condition: service_healthy
      notification-daemon:
        condition: service_healthy
      status-transition-daemon:
        condition: service_healthy
      retry-daemon:
        condition: service_healthy
    environment:
      NGINX_LOG_LEVEL: debug

  postgres:
    command: [
      "postgres",
      "-c", "log_min_messages=debug1"
    ]

  rabbitmq:
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,debug}]

  redis:
    command: valkey-server --appendonly yes --loglevel debug

networks:
  app-network:
    name: swag_game_scheduler
    driver: bridge
    external: true
