# Production overrides - use with --env-file env/env.prod
# Minimal overrides since compose.yaml provides production-ready defaults
#
# Usage: docker compose --env-file env/env.prod up -d
#
# Production configuration:
# - LOG_LEVEL: INFO (from compose.yaml base)
# - restart: always (from compose.yaml base)
# - No port mappings (reverse proxy handles external access)
# - Production build targets from Dockerfiles

services:
  api:
    build:
      target: production

  bot:
    build:
      target: production

  notification-daemon:
    build:
      target: production

  status-transition-daemon:
    build:
      target: production

  frontend:
    build:
      target: production
