# End-to-end test overrides - use with --env-file env/env.e2e
# Tests complete notification flow including Discord bot interactions
#
# Usage:
#   Run all tests: ./scripts/run-e2e-tests.sh
#   Run specific test: ./scripts/run-e2e-tests.sh tests/e2e/test_game_announcement.py -v
#
# E2E test configuration:
# - LOG_LEVEL: DEBUG for all services
# - No port mappings (tests run inside container network)
# - tmpfs volumes for speed
# - Test service with full dependencies
#
# Note: Container ENTRYPOINT is 'pytest', so pass pytest args directly (not 'pytest' itself)

services:
  init:
    volumes: []
    environment:
      TEST_ENVIRONMENT: ${TEST_ENVIRONMENT}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_ADMIN_BOT_TOKEN: ${DISCORD_ADMIN_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      DISCORD_USER_ID: ${DISCORD_USER_ID}
      PYTEST_RUNNING: "1"

  api:
    build:
      target: production
    volumes: []
    environment:
      LOG_LEVEL: DEBUG
      DISCORD_BOT_TOKEN: ${DISCORD_TOKEN}
      PYTEST_RUNNING: "1"

  bot:
    build:
      target: production
    volumes: []
    environment:
      LOG_LEVEL: DEBUG
      DISCORD_BOT_TOKEN: ${DISCORD_TOKEN}
      PYTEST_RUNNING: "1"

  notification-daemon:
    build:
      target: production
    volumes: []
    environment:
      LOG_LEVEL: DEBUG
      PYTEST_RUNNING: "1"

  status-transition-daemon:
    build:
      target: production
    volumes: []
    environment:
      LOG_LEVEL: DEBUG
      PYTEST_RUNNING: "1"

  postgres:
    command: [
      "postgres",
      "-c", "log_min_messages=debug1"
    ]

  rabbitmq:
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,debug}]

  redis:
    command: valkey-server --appendonly yes --loglevel debug

  system-ready:
    image: alpine:latest
    container_name: ${CONTAINER_PREFIX:-gamebot-e2e}-system-ready
    command: sh -c "echo 'System ready for testing' && sleep infinity"
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started
      bot:
        condition: service_started
      notification-daemon:
        condition: service_started
      status-transition-daemon:
        condition: service_started
      retry-daemon:
        condition: service_started
    networks:
      - app-network
    restart: "no"

  e2e-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: ${CONTAINER_PREFIX:-gamebot-e2e}-tests
    environment:
      PYTHONUNBUFFERED: \"1\"
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      API_BASE_URL: http://api:8000
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_ADMIN_BOT_TOKEN: ${DISCORD_ADMIN_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      DISCORD_USER_ID: ${DISCORD_USER_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TEST_ENVIRONMENT: ${TEST_ENVIRONMENT}
    depends_on:
      system-ready:
        condition: service_started
    networks:
      - app-network
    command: tests/e2e/ -v --tb=short

# Use tmpfs for test volumes (in-memory, fast, auto-cleanup)
volumes:
  postgres_data:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-postgres-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  rabbitmq_data:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-rabbitmq-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_data:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-redis-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  app-network:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-test-network
    driver: bridge
