# End-to-end test environment configuration
# Uses base service definitions from compose.yaml via merge pattern
#
# Usage: docker compose -f docker-compose.e2e.yml --env-file .env.e2e up --abort-on-container-exit
#
# Tests complete notification flow including Discord bot interactions

services:
  e2e-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: ${CONTAINER_PREFIX:-gamebot-e2e}-tests
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      REDIS_URL: ${REDIS_URL}
      API_BASE_URL: http://api:8000
      TEST_DISCORD_TOKEN: ${TEST_DISCORD_TOKEN}
      TEST_DISCORD_GUILD_ID: ${TEST_DISCORD_GUILD_ID}
      TEST_DISCORD_CHANNEL_ID: ${TEST_DISCORD_CHANNEL_ID}
      TEST_DISCORD_USER_ID: ${TEST_DISCORD_USER_ID}
      TEST_ENVIRONMENT: ${TEST_ENVIRONMENT}
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started
      bot:
        condition: service_started
      notification-daemon:
        condition: service_started
    networks:
      - app-network
    command: pytest tests/e2e/test_game_notification_api_flow.py -v --tb=short

# Use tmpfs for test volumes (in-memory, fast, auto-cleanup)
volumes:
  postgres_data:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-postgres-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  rabbitmq_data:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-rabbitmq-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_data:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-redis-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  app-network:
    name: ${CONTAINER_PREFIX:-gamebot-e2e}-test-network
    driver: bridge
