# Integration test environment configuration
# Uses base service definitions from compose.yaml via merge pattern
#
# Usage: 
#   Run all tests: ./scripts/run-integration-tests.sh
#   Run specific test: ./scripts/run-integration-tests.sh tests/integration/test_retry_daemon.py -v
#
# Note: Container ENTRYPOINT is 'pytest', so pass pytest args directly (not 'pytest' itself)

services:
  integration-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: ${CONTAINER_PREFIX:-gamebot-integration}-tests
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      REDIS_URL: ${REDIS_URL}
      TEST_ENVIRONMENT: ${TEST_ENVIRONMENT}
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      retry-daemon:
        condition: service_started
    networks:
      - app-network
    command: tests/integration/ -v --tb=short

# Use tmpfs for test volumes (in-memory, fast, auto-cleanup)
volumes:
  postgres_data:
    name: ${CONTAINER_PREFIX:-gamebot-integration}-postgres-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  rabbitmq_data:
    name: ${CONTAINER_PREFIX:-gamebot-integration}-rabbitmq-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_data:
    name: ${CONTAINER_PREFIX:-gamebot-integration}-redis-data
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  app-network:
    name: ${CONTAINER_PREFIX:-gamebot-integration}-test-network
    driver: bridge
