# Development overrides - automatically loaded by Docker Compose
# This file enables instant code changes without container rebuilds
#
# Usage: docker compose up (automatically uses this file)
#
# Development configuration:
# - LOG_LEVEL: DEBUG for all services
# - All ports exposed (app + infrastructure management)
# - Source code mounted as volumes for hot-reload
# - Development build targets
#
# IMPORTANT: Source files must be world-readable (chmod o+r) for the container
# user (UID 1000) to access volume-mounted code

services:
  api:
    build:
      target: development
    volumes:
      - ./shared:/app/shared:ro
      - ./services/api:/app/services/api:ro
    command: uvicorn services.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${API_HOST_PORT:-8000}:8000"
    environment:
      LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: "1"

  bot:
    build:
      target: development
    volumes:
      - ./shared:/app/shared:ro
      - ./services/bot:/app/services/bot:ro
    environment:
      LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: "1"

  notification-daemon:
    build:
      target: development
    volumes:
      - ./shared:/app/shared:ro
      - ./services/scheduler:/app/services/scheduler:ro
    environment:
      LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: "1"

  status-transition-daemon:
    build:
      target: development
    volumes:
      - ./shared:/app/shared:ro
      - ./services/scheduler:/app/services/scheduler:ro
    environment:
      LOG_LEVEL: DEBUG
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      target: development
      args:
        VITE_DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
        VITE_API_URL: ${API_URL:-http://localhost:8000}
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json:ro
    command: npm run dev -- --host 0.0.0.0 --port 80
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:80"
    environment:
      VITE_API_URL: ${API_URL:-http://localhost:8000}
      VITE_DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}

  postgres:
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    command: [
      "postgres",
      "-c", "log_min_messages=debug1"
    ]

  rabbitmq:
    ports:
      - "${RABBITMQ_DATA_HOST_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_HOST_PORT:-15672}:15672"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,debug}]

  redis:
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    command: redis-server --appendonly yes --loglevel debug

  grafana-alloy:
    ports:
      - "${ALLOY_HOST_PORT:-12345}:12345"
