# Copyright 2025 Bret McKee (bret.mckee@gmail.com)
#
# This file is part of Game_Scheduler. (https://github.com/game-scheduler)
#
# Game_Scheduler is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# Game_Scheduler is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with Game_Scheduler If not, see <https://www.gnu.org/licenses/>.


"""Remove is_pre_populated field from game_participants

Revision ID: 14d77a523f0a
Revises: 010_remove_status_field
Create Date: 2025-11-22 12:40:35.477511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d77a523f0a'
down_revision: Union[str, None] = '010_remove_status_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channel_configurations_channel_id_key'), 'channel_configurations', type_='unique')
    op.drop_index(op.f('ix_channel_configurations_channel_id'), table_name='channel_configurations')
    op.create_index(op.f('ix_channel_configurations_channel_id'), 'channel_configurations', ['channel_id'], unique=True)
    op.drop_column('game_participants', 'is_pre_populated')
    op.drop_constraint(op.f('guild_configurations_guild_id_key'), 'guild_configurations', type_='unique')
    op.drop_index(op.f('ix_guild_configurations_guild_id'), table_name='guild_configurations')
    op.create_index(op.f('ix_guild_configurations_guild_id'), 'guild_configurations', ['guild_id'], unique=True)
    op.drop_constraint(op.f('users_discord_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=False)
    op.create_unique_constraint(op.f('users_discord_id_key'), 'users', ['discord_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_guild_configurations_guild_id'), table_name='guild_configurations')
    op.create_index(op.f('ix_guild_configurations_guild_id'), 'guild_configurations', ['guild_id'], unique=False)
    op.create_unique_constraint(op.f('guild_configurations_guild_id_key'), 'guild_configurations', ['guild_id'], postgresql_nulls_not_distinct=False)
    op.add_column('game_participants', sa.Column('is_pre_populated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_channel_configurations_channel_id'), table_name='channel_configurations')
    op.create_index(op.f('ix_channel_configurations_channel_id'), 'channel_configurations', ['channel_id'], unique=False)
    op.create_unique_constraint(op.f('channel_configurations_channel_id_key'), 'channel_configurations', ['channel_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
